"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<Language, string>> = {
    "app.title": { en: "EGX Bots", ar: "EGX Bots" },
    "app.subtitle": { 
        en: "AI-powered stock insights to help you spot opportunities with confidence", 
        ar: "رؤى الأسهم المدعومة بالذكاء الاصطناعي لمساعدتك على رصد الفرص الاستثمارية بثقة" 
    },
    "ticker.label": { en: "Ticker", ar: "الرمز" },
    "ticker.placeholder": { en: "AAPL", ar: "AAPL" },
    "btn.run": { en: "Run prediction", ar: "تشغيل التوقع" },
    "btn.running": { en: "Running...", ar: "جاري التشغيل..." },
    "btn.browse": { en: "Browse", ar: "تصفح" },
    "browse.title": { en: "Browse Symbols", ar: "تصفح الرموز" },
    "dialog.country": { en: "Country", ar: "الدولة" },
    "dialog.select_country": { en: "Select a country...", ar: "اختر دولة..." },
    "dialog.search_placeholder": { en: "Search by symbol or name...", ar: "ابحث بالرمز أو الاسم..." },
    "dialog.search_btn": { en: "Search", ar: "بحث" },
    "result.precision": { en: "Precision", ar: "الدقة" },
    "result.window": { en: "Test window", ar: "نافذة الاختبار" },
    "result.last_close": { en: "Last Close", ar: "آخر سعر إغلاق" },
    "result.date": { en: "Date", ar: "التاريخ" },
    "result.signal": { en: "Tomorrow Signal", ar: "إشارة الغد" },
    "chart.title": { en: "{symbol} Chart Analysis", ar: "تحليل مخطط {symbol}" },
    "signal.up": { en: "Up (buy candidate)", ar: "صعود (مرشح للشراء)" },
    "signal.down": { en: "Down/flat (avoid)", ar: "هبوط/استقرار (تجنب)" },
    "nav.scanner.ai": { en: "AI Scanner", ar: "الماسح الذكي" },
    "nav.scanner.ai_trading": { en: "stocks score", ar: "تقييم الأسهم" },
    "nav.scanner.tech": { en: "Technical Scanner", ar: "الماسح الفني" },
    "nav.scanner.backtests": { en: "Strategy Simulator", ar: "محاكاة الأداء التاريخي" },
    "nav.scanner.similarity": { en: "Historical Similarity", ar: "النماذج المتكررة (شبه ده)" },
    "nav.scanner.market": { en: "Market Analysis", ar: "اتجاه السوق والعملة" },
    "nav.scanner.compare": { en: "Comparison", ar: "المقارنة" },
    
    // Market Analysis Translations
    "market.title": { en: "Market Analysis", ar: "تحليل اتجاه السوق والوضع الاقتصادي" },
    "market.subtitle": { en: "Analyzing EGX30, EGX100, and USD/EGP rate to dynamically adjust bot strategy.", ar: "تحليل حركة مؤشري البورصة المصرية وسعر صرف الدولار لتحديث سلوك البوت تلقائياً." },
    "market.last_updated": { en: "Last updated:", ar: "آخر تحديث:" },
    "market.egx30_card": { en: "EGX 30 Index", ar: "مؤشر إيجي إكس 30" },
    "market.egx100_card": { en: "EGX 100 Index", ar: "مؤشر إيجي إكس 100" },
    "market.usdegp_card": { en: "USD/EGP Exchange Rate", ar: "سعر صرف الدولار (USD/EGP)" },
    "market.points": { en: "points", ar: "نقطة" },
    "market.egp": { en: "EGP", ar: "جنيه" },
    "market.regime_label": { en: "Current Market Regime:", ar: "وضع السوق الحالي:" },
    "market.buy_paused": { en: "Buy Inflow Paused ⛔", ar: "تعليق الشراء نشط ⛔" },
    "market.no_data": { en: "No chart data available from EODHD.", ar: "لا توجد بيانات مخطط متاحة من EODHD." },
    "market.tab_egx30_desc": { en: "EGX 30 Index Trend (180d)", ar: "حركة مؤشر EGX 30 التاريخية (180 يوم)" },
    "market.tab_egx100_desc": { en: "EGX 100 Index Trend (180d)", ar: "حركة مؤشر EGX 100 التاريخية (180 يوم)" },
    "market.tab_usdegp_desc": { en: "USD/EGP Exchange Rate Trend (180d)", ar: "سعر صرف الدولار أمام الجنيه المصري (180 يوم)" },
    "market.regime.panic.title": { en: "Panic / High Volatility Downside 🚨", ar: "حالة ذعر وهبوط حاد (Panic Regime) 🚨" },
    "market.regime.panic.desc": { en: "The system automatically suspends buy suggestions to protect portfolios during sharp market panic phases.", ar: "يقوم نظام البوت بتعليق اقتراحات الشراء تلقائياً لحماية المحفظة من الانعكاسات الحادة للسوق." },
    "market.regime.trending_up.title": { en: "Strong Bullish Trend 🚀", ar: "اتجاه صاعد قوي (Trending Up) 🚀" },
    "market.regime.trending_up.desc": { en: "EGX is experiencing strong buying inflows. The trading system increases model confidence filters for breakouts.", ar: "البورصة المصرية تشهد تدفقات شرائية قوية. البوت يرفع درجات الثقة ويعزز صفقات الاختراق." },
    "market.regime.trending_down.title": { en: "Bearish Trend 📉", ar: "اتجاه هابط (Trending Down) 📉" },
    "market.regime.trending_down.desc": { en: "Market liquidity is declining. Recommend scaling down trade sizes and targeting only exceptional strength stocks.", ar: "سيولة السوق متراجعة. ينصح بتقليل كميات التداول والتركيز فقط على الأسهم ذات القوة النسبية الاستثنائية." },
    "market.regime.sideways.title": { en: "Sideways / Rangebound ⚖️", ar: "تذبذب عرضي / تجميع (Sideways / Accumulation) ⚖️" },
    "market.regime.sideways.desc": { en: "Market is balanced. Focus on buying key support and selling resistance zones until a clear breakout occurs.", ar: "حركة السوق متوازنة. نركز على استراتيجيات الشراء من الدعم والبيع عند المقاومة حتى حدوث اختراق واضح." },
    "market.regime.fallback.title": { en: "Sideways Market", ar: "وضع تذبذب عرضي" },
    "market.regime.fallback.desc": { en: "Main indices are moving in a rangebound sideways fashion.", ar: "المؤشرات الرئيسية تتحرك بشكل عرضي متذبذب." },
    
    "market.maker_title": { en: "Market Maker Depth & Volume Analysis", ar: "تحليل صانع السوق (Accumulation & Distribution)" },
    "market.maker_intro": { en: "The market maker controls stock cycles through two primary phases:", ar: "يتحكم صانع السوق (The Maker) في حركة الأسهم من خلال دورتين رئيسيتين:" },
    "market.maker_accum_title": { en: "1. Accumulation Phase:", ar: "1. مرحلة التجميع (Accumulation):" },
    "market.maker_accum_desc": { en: "Occurs at support levels. Characterized by low price volatility and steady volume accumulation before a breakout.", ar: "تحدث في مناطق الدعم أو المسارات العرضية. تتميز بحجم تداول هادئ وتذبذب سعري منخفض، حيث يتم تجميع الكميات دون لفت الأنظار قبل الاختراق لأعلى." },
    "market.maker_dist_title": { en: "2. Distribution Phase:", ar: "2. مرحلة التصريف (Distribution):" },
    "market.maker_dist_desc": { en: "Occurs at peak resistance levels. Characterized by high trading volume spikes, high volatility, and failed attempts to break new highs, signaling distribution.", ar: "تحدث في القمم وبجوار مستويات المقاومة الرئيسية. تتميز بزيادة حادة في حجم التداول مع تذبذب سعري كبير وفشل السهم في تحقيق قمم أعلى، وهو ما ينذر بالتصريف والهبوط لاحقاً." },
    "market.maker_tip": { en: "The system utilizes ADX trend strength and liquidity indicators (OBV/MFI) to differentiate accumulation from distribution.", ar: "البوت يستعين بمؤشر ADX لحساب قوة الاتجاه ومؤشرات السيولة (MFI/OBV) للتفرقة بين التجميع والتصريف لمنع الدخول العشوائي في نهاية موجات الصعود." },
    
    "market.macro_title": { en: "USD/EGP Exchange Rate & Macro Correlation", ar: "تأثير سعر الصرف والاقتصاد الكلي على البورصة" },
    "market.macro_intro": { en: "Historically, there is a strong positive correlation between a rising USD/EGP rate and rallies in the EGX30 index:", ar: "هناك علاقة طردية قوية تاريخياً بين ارتفاع سعر صرف الدولار (انخفاض قيمة الجنيه) وصعود مؤشر البورصة المصرية EGX30:" },
    "market.macro_hedge_title": { en: "1. Inflation Hedge:", ar: "1. تحوط ضد التضخم (Inflation Hedge):" },
    "market.macro_hedge_desc": { en: "Investors purchase stocks as tangibles to preserve capital during devaluations, boosting corporate valuations on paper.", ar: "يقوم المستثمرون والمؤسسات بضخ السيولة في الأسهم كأصول عينية للتحوط من تآكل العملة المحلية، مما يدفع مؤشر EGX30 لصعود قياسي." },
    "market.macro_reval_title": { en: "2. Asset Revaluation:", ar: "2. إعادة تقييم الأصول (Asset Revaluation):" },
    "market.macro_reval_desc": { en: "Companies with USD-denominated revenues (ex. petrochemicals, fertilizers, logistics) see immediate market cap adjustments.", ar: "الشركات الكبرى المدرجة (خصوصاً ذات الأرباح أو الإيرادات الدولارية كالبتروكيماويات والأسمدة والشحن) ترتفع قيمتها السوقية فوراً بما يعادل تغيير سعر الصرف." },
    "market.macro_tip": { en: "During currency adjustments, the model biases weight allocation toward export-heavy firms and EGX30 bellwethers.", ar: "عند ارتفاع الدولار، يميل البوت إلى إعطاء وزن أكبر لأسهم التصدير والشركات القيادية لأنها تستفيد بشكل مباشر من إعادة تقييم الأصول السعري." },
    "nav.home": { en: "Home", ar: "الرئيسية" },
    "nav.leaderboard": { en: "Leaderboard", ar: "لوحة الصدارة" },
    "nav.pricing": { en: "Pricing", ar: "الأسعار" },
    "nav.profile": { en: "Profile", ar: "الملف الشخصي" },
    "auth.login": { en: "Login", ar: "تسجيل الدخول" },
    "auth.logout": { en: "Logout", ar: "تسجيل الخروج" },
    "header.pro_analysis": { en: "Analysis", ar: "التحليل" },
    "account.label": { en: "Account", ar: "الحساب" },
    "compare.symbol": { en: "Symbol", ar: "الرمز" },
    "compare.precision": { en: "AI Precision", ar: "دقة الذكاء الاصطناعي" },
    "compare.rsi": { en: "RSI Stats", ar: "إحصائيات RSI" },
    "compare.macd": { en: "MACD Stats", ar: "إحصائيات MACD" },
    "compare.ema": { en: "EMA Cross", ar: "تقاطع EMA" },
    "compare.bb": { en: "Bollinger", ar: "بولنجر" },
    "compare.actions": { en: "Actions", ar: "الإجراءات" },
    "compare.empty": { en: "Add symbols to compare their performance statistics.", ar: "أضف رموزاً لمقارنة إحصائيات أدائها." },
    "compare.fetching": { en: "Fetching historical data and calculating statistics...", ar: "جاري جلب البيانات التاريخية وحساب الإحصائيات..." },
    "compare.winrate_info": { 
        en: "Win rates are calculated by matching indicator signals against actual next-day price movement (UP/DOWN).", 
        ar: "يتم حساب نسب النجاح بمطابقة إشارات المؤشرات مع حركة السعر الفعلية لليوم التالي (صعود/هبوط)." 
    },
    "tech.title": { en: "Technical Scanner", ar: "الماسح الفني" },
    "tech.subtitle": { en: "Advanced technical screener with real-time indicators.", ar: "فاحص فني متقدم مع مؤشرات فورية." },
    "tech.config": { en: "Scanner Config", ar: "إعدادات الماسح" },
    "tech.market": { en: "Market", ar: "السوق" },
    "tech.rsi": { en: "RSI (14)", ar: "RSI (14)" },
    "tech.adx": { en: "ADX (14)", ar: "ADX (14)" },
    "tech.atr": { en: "ATR (14)", ar: "ATR (14)" },
    "tech.stoch": { en: "Stoch %K (14)", ar: "Stoch %K (14)" },
    "tech.roc": { en: "ROC (12)", ar: "ROC (12)" },
    "tech.price_above_ema50": { en: "Price > EMA 50", ar: "السعر > EMA 50" },
    "tech.price_above_ema200": { en: "Price > EMA 200", ar: "السعر > EMA 200" },
    "tech.golden_cross": { en: "Golden Cross (50 > 200)", ar: "التقاطع الذهبي (50 > 200)" },
    "tech.price_above_vwap20": { en: "Price > VWAP 20", ar: "السعر > VWAP 20" },
    "tech.volume_spike": { en: "Volume Spike (> SMA20)", ar: "طفرة في حجم التداول (> SMA20)" },
    "tech.start_scan": { en: "Start Scan", ar: "بدء الفحص" },
    "tech.stop_scan": { en: "Stop Scanning", ar: "إيقاف الفحص" },
    "tech.quick_search": { en: "Quick search...", ar: "بحث سريع..." },
    "tech.found_matches": { en: "Found {count} matches", ar: "تم العثور على {count} من المطابقات" },
    "tech.clear_results": { en: "Clear Results", ar: "مسح النتائج" },
    "tech.restore_last": { en: "Restore Last", ar: "استعادة الأخير" },
    "tech.ready": { en: "Ready to scan. Configure filters and press Start.", ar: "جاهز للفحص. قم بتهيئة الفلاتر واضغط بدء." },
    "tech.no_matches": { en: "No stocks match your criteria.", ar: "لا توجد أسهم تطابق المعايير الخاصة بك." },
    "tech.table.symbol": { en: "Symbol", ar: "الرمز" },
    "tech.table.price": { en: "Price", ar: "السعر" },
    "tech.table.momentum": { en: "Momentum", ar: "الزخم" },
    "tech.table.save": { en: "Save", ar: "حفظ" },
    "pagination.page": { en: "Page", ar: "الصفحة" },
    "dash.title": { en: "Market Strategy Dashboard", ar: "لوحة تحكم استراتيجية السوق" },
    "dash.subtitle": { 
        en: "Aggregate success rates for key technical indicators across {country} market listings.", 
        ar: "معدلات النجاح الإجمالية للمؤشرات الفنية الرئيسية عبر قوائم سوق {country}." 
    },
    "dash.winrate": { en: "Avg Win Rate", ar: "متوسط نسبة النجاح" },
    "dash.signals": { en: "Total Signals", ar: "إجمالي الإشارات" },
    "dash.scanned": { en: "Scanned {count} tickers", ar: "تم فحص {count} رمزاً" },
    "dash.refresh": { en: "Refreshed {time} ago", ar: "تم التحديث منذ {time}" },
    "dash.filter_market": { en: "Filter Market", ar: "تصفية السوق" },
    "ai.title": { en: "AI Market Scanner", ar: "الماسح الذكي للسوق" },
    "ai.subtitle": { 
        en: "Scans the market using the Random Forest model to find high-probability BUY signals.", 
        ar: "يفحص السوق باستخدام نموذج الغابة العشوائية للعثور على إشارات شراء عالية الاحتمالية." 
    },
    "ai.scan_all": { en: "Scan All Market", ar: "فحص السوق بالكامل" },
    "ai.start_scan": { en: "Start AI Scan", ar: "بدء الفحص الذكي" },
    "ai.stop_scan": { en: "Stop Analysis", ar: "إيقاف التحليل" },
    "ai.model_preset": { en: "Model Preset", ar: "النموذج المسبق" },
    "ai.model_options": { en: "Model Options", ar: "خيارات النموذج" },
    "ai.precision_info": { 
        en: "Precision means: among all signals produced in backtest, how many were correct. High precision usually indicates higher quality.", 
        ar: "الدقة تعني: من بين جميع الإشارات المنتجة في الباك تيست، كم منها كان صحيحاً. الدقة العالية تشير عادة إلى جودة أعلى." 
    },
    "ai.matches": { en: "Matches", ar: "المطابقات" },
    "ai.table.symbol": { en: "Symbol", ar: "الرمز" },
    "ai.table.name": { en: "Name", ar: "الاسم" },
    "ai.table.price": { en: "Last Price", ar: "آخر سعر" },
    "ai.table.precision": { en: "AI Precision", ar: "دقة الذكاء الاصطناعي" },
    "ai.table.save": { en: "Save", ar: "حفظ" },
    "ai.no_matches": { en: "No high-confidence opportunities found in this batch.", ar: "لم يتم العثور على فرص عالية الثقة في هذه الدفعة." },
    "ai.chart_ctrl": { en: "Chart View", ar: "عرض المخطط" },
    "ai.indicators": { en: "Indicators", ar: "المؤشرات" },
    "scanner.templates.kicker": { en: "One-Click Strategies", ar: "استراتيجيات بنقرة واحدة" },
    "scanner.templates.title": { en: "Scanner Templates", ar: "قوالب الماسح" },
    "scanner.templates.subtitle": { en: "Pick a strategy to launch a focused scan instantly.", ar: "اختر استراتيجية لإطلاق فحص مركز على الفور." },
    "scanner.templates.ai_growth.title": { en: "AI Smart Pick", ar: "الاختيار الذكي للذكاء الاصطناعي" },
    "scanner.templates.ai_growth.desc": { 
        en: "AI expects upside based on a Random Forest model trained on two years of data.", 
        ar: "يتوقع الذكاء الاصطناعي صعوداً بناءً على نموذج الغابة العشوائية المدرب على بيانات عامين." 
    },
    "scanner.templates.macd_cross.title": { en: "MACD Golden Cross", ar: "التقاطع الذهبي لـ MACD" },
    "scanner.templates.macd_cross.desc": { en: "Classic entry when MACD crosses its signal line to the upside.", ar: "دخول كلاسيكي عندما يتقاطع خط MACD مع خط الإشارة الخاص به للأعلى." },
    "scanner.templates.rsi_oversold.title": { en: "RSI Oversold", ar: "RSI منطقة ذروة البيع" },
    "scanner.templates.rsi_oversold.desc": { en: "Find tickers under RSI 30 that may be ready to rebound.", ar: "ابحث عن الرموز الأقل من RSI 30 والتي قد تكون جاهزة للارتداد." },
    "scanner.templates.volume_breakout.title": { en: "Volume Breakout", ar: "اختراق حجم التداول" },
    "scanner.templates.volume_breakout.desc": { en: "Detect unusual volume spikes signaling institutional interest.", ar: "رصد الارتفاعات غير العادية في حجم التداول التي تشير إلى اهتمام المؤسسات." },
    "scanner.templates.sma_200_breakout.title": { en: "Trend Breakout", ar: "اختراق الاتجاه" },
    "scanner.templates.sma_200_breakout.desc": { en: "Price breaks above the 200-day SMA to confirm a long-term uptrend.", ar: "يخترق السعر خط SMA لـ 200 يوم لتأكيد اتجاه صعودي طويل المدى." },
    "scanner.templates.risk.low": { en: "Low Risk", ar: "مخاطر منخفضة" },
    "scanner.templates.risk.medium": { en: "Medium Risk", ar: "مخاطر متوسطة" },
    "scanner.templates.risk.high": { en: "High Risk", ar: "مخاطر عالية" },
    "scanner.templates.risk.very_high": { en: "Very High Risk", ar: "مخاطر عالية جداً" },
    "profile.track": { en: "Track positions, targets, stop-loss and performance.", ar: "تتبع المراكز والأهداف ووقف الخسارة والأداء." },
    "profile.stats.open": { en: "Open", ar: "المفتوحة" },
    "profile.stats.wins": { en: "Wins", ar: "الرابحة" },
    "profile.stats.losses": { en: "Losses", ar: "الخاسرة" },
    "profile.stats.winrate": { en: "Win Rate", ar: "نسبة النجاح" },
    "profile.defaults.title": { en: "Trading Defaults", ar: "القيم الافتراضية للتداول" },
    "profile.defaults.subtitle": { en: "Used when saving a new symbol to your watchlist.", ar: "تستخدم عند حفظ رمز جديد في قائمة المراقبة." },
    "profile.defaults.target": { en: "Default Target %", ar: "الهدف الافتراضي %" },
    "profile.defaults.stop": { en: "Default Stop-Loss %", ar: "وقف الخسارة الافتراضي %" },
    "profile.ai.title": { en: "AI Assistant Settings", ar: "إعدادات مساعد الذكاء الاصطناعي" },
    "profile.ai.subtitle": { en: "Configure API keys for the smart chat assistant.", ar: "تكوين مفاتيح واجهة برمجة التطبيقات لمساعد الدردشة الذكي." },
    "profile.ai.gemini": { en: "Gemini API Key", ar: "مفتاح Gemini API" },
    "profile.ai.rules": { en: "Custom Rules / Instructions", ar: "القواعد المخصصة / التعليمات" },
    "profile.positions.title": { en: "Trading Positions", ar: "مراكز التداول" },
    "profile.positions.subtitle": { en: "Manage your open and closed positions. Evaluation updates status to Win/Loss.", ar: "إدارة مراكزك المفتوحة والمغلقة. التقييم يحدث الحالة إلى ربح/خسارة." },
    "profile.positions.evaluate": { en: "Evaluate Open Positions", ar: "تقييم المراكز المفتوحة" },
    "profile.table.symbol": { en: "Symbol", ar: "الرمز" },
    "profile.table.added": { en: "Added", ar: "تاريخ الإضافة" },
    "profile.table.status": { en: "Status", ar: "الحالة" },
    "profile.table.entry": { en: "Entry", ar: "سعر الدخول" },
    "profile.table.target": { en: "Target", ar: "الهدف" },
    "profile.table.stop": { en: "Stop", ar: "وقف الخسارة" },
    "profile.table.actions": { en: "Actions", ar: "الإجراءات" },
    "home.insights.title": { en: "Smart AI Insights", ar: "رؤى الذكاء الاصطناعي الذكية" },
    "home.insights.subtitle": { en: "Combined Fundamental & Technical Analysis", ar: "التحليل الفني والأساسي المشترك" },
    "home.insights.valuation": { en: "Valuation", ar: "التقييم" },
    "home.insights.volatility": { en: "Volatility Risk", ar: "مخاطر التقلب" },
    "home.insights.mcap": { en: "Market Cap", ar: "القيمة السوقية" },
    "home.insights.undervalued": { en: "Undervalued. Good value stock candidate.", ar: "أقل من قيمته الحقيقية. مرشح كقيمة جيدة لسهم." },
    "home.insights.fair": { en: "Fair Valuation. Market standard.", ar: "تقييم عادل. معيار السوق." },
    "home.insights.expensive": { en: "Growth/Expensive. Expect volatility.", ar: "نمو/مرتفع القيمة. توقع تقلبات." },
    "home.insights.bubble": { en: "Very Expensive (Bubble risk?). AI is cautious.", ar: "غالٍ جداً (خطر فقاعة؟). الذكاء الاصطناعي حذر." },
    "home.insights.low_vol": { en: "Low Volatility. Defensive / Safe haven.", ar: "تقلب منخفض. دفاعي / ملاذ آمن." },
    "home.insights.avg_vol": { en: "Average Market Risk.", ar: "مخاطر سوق متوسطة." },
    "home.insights.high_vol": { en: "High Volatility. High risk/reward.", ar: "تقلبات عالية. مخاطرة وعائد مرتفعان." },
    "home.insights.large_cap": { en: "Large Cap. Stable & Established.", ar: "قيمة سوقية ضخمة. مستقر وراسخ." },
    "home.insights.mid_cap": { en: "Mid Cap. Balanced Growth.", ar: "قيمة سوقية متوسطة. نمو متوازن." },
    "home.insights.small_cap": { en: "Small Cap. Higher growth potential but risky.", ar: "قيمة سوقية صغيرة. إمكانية نمو أعلى ولكن محفوفة بالمخاطر." },
    "home.insights.strong_buy": { en: "Strong Buy Signal: Technical Uptrend + Reasonable Valuation.", ar: "إشارة شراء قوية: اتجاه فني صاعد + تقييم معقول." },
    "home.insights.cautious_buy": { en: "Cautious Buy: Technical Uptrend, but Valuation is expensive.", ar: "شراء حذر: اتجاه فني صاعد، لكن التقييم مرتفع." },
    "home.chart.title": { en: "Price & AI Buy Signals", ar: "الأسعار وإشارات الشراء للذكاء الاصطناعي" },
    "home.chart.subtitle": { en: "Green dots are model buy predictions", ar: "النقاط الخضراء هي توقعات شراء النموذج" },
    "home.fundamentals.title": { en: "Fundamentals", ar: "البيانات الأساسية" },
    "home.footer.disclaimer": { en: "Model output is not financial advice.", ar: "مخرجات النموذج ليست نصيحة مالية." },
    "dash.days.30": { en: "Last 30 Days", ar: "آخر 30 يوماً" },
    "dash.days.60": { en: "Last 60 Days", ar: "آخر 60 يوماً" },
    "dash.days.90": { en: "Last 90 Days", ar: "آخر 90 يوماً" },
    "compare.save": { en: "Save", ar: "حفظ" },
    "compare.saved": { en: "Saved", ar: "تم الحفظ" },
    "compare.chart": { en: "Chart", ar: "المخطط" },
    "chart.close": { en: "Close", ar: "إغلاق" },
    "backtest.title": { en: "Backtest Results", ar: "نتائج الاختبارات العكسية" },
    "backtest.subtitle": { en: "Compare historical performance and simulation statistics of our quantitative AI trading models.", ar: "مقارنة الأداء التاريخي وإحصائيات المحاكاة لنماذج التداول بالذكاء الاصطناعي." },
    "backtest.no_results": { en: "No backtest results found for the Egyptian market.", ar: "لم يتم العثور على نتائج اختبارات عكسية للسوق المصري." },
    "backtest.detailed_logs": { en: "No detailed trade entries available for this run.", ar: "لا توجد تفاصيل صفقات متاحة لهذا التشغيل." },
    "backtest.filtered": { en: "Filtered", ar: "مصفى" },
    "backtest.raw_data": { en: "Raw Data", ar: "البيانات الخام" },
    "backtest.summary": { en: "Summary", ar: "الملخص" },
    "backtest.trades": { en: "Trades", ar: "الصفقات" },
    "backtest.trades_count": { en: "{count} Trades", ar: "{count} صفقة" },
    "backtest.chart": { en: "Chart", ar: "المخطط" },
    "bots.title": { en: "Active Trading Bots", ar: "بوتات التداول النشطة" },
    "bots.subtitle": { en: "Subscribe to receive real-time signals on Telegram", ar: "اشترك لتلقي الإشارات الفورية على تليجرام" },
    "bots.no_active": { en: "No active trading bots are currently running.", ar: "لا توجد بوتات تداول نشطة تعمل حالياً." },
    "model.artifacts": { en: "Model Artifacts", ar: "ملفات النماذج الذكية" },
    "model.available": { en: "Available .pkl Modules", ar: "ملفات النماذج بصيغة .pkl المتاحة" },
    "bots.free_limit": { en: "Your Bot Subscriptions: {count} / 2 (Free Plan Limit)", ar: "اشتراكات البوت الخاصة بك: {count} / 2 (الحد الأقصى للخطة المجانية)" },
    "backtest.model_evaluation": { en: "Model Evaluation", ar: "تقييم النموذج" },
    "backtest.artificial_intelligence": { en: "Artificial Intelligence", ar: "الذكاء الاصطناعي" },
    "backtest.standard_run": { en: "Standard Run", ar: "تشغيل قياسي" },
    "backtest.optimizer_run": { en: "Optimizer Run", ar: "تشغيل المحسِّن" },
    "backtest.live_bot_run": { en: "Live Bot Execution", ar: "تنفيذ البوت المباشر" },
    "bots.table.identity": { en: "Bot Identity", ar: "هوية البوت" },
    "bots.table.status": { en: "Status", ar: "الحالة" },
    "bots.table.mode": { en: "Mode", ar: "النمط" },
    "bots.table.config": { en: "Config", ar: "الإعدادات" },
    "bots.table.model": { en: "Model", ar: "النموذج" },
    "bots.table.trades": { en: "Trades", ar: "الصفقات" },
    "bots.table.winrate": { en: "Win Rate", ar: "نسبة النجاح" },
    "bots.table.net_pl": { en: "Net P/L", ar: "صافي الأرباح/الخسائر" },
    "bots.table.action": { en: "Action", ar: "الإجراء" },
    "bots.status.running": { en: "Running", ar: "يعمل" },
    "bots.status.stopped": { en: "Stopped", ar: "متوقف" },
    "bots.btn.subscribe": { en: "Subscribe", ar: "اشتراك" },
    "bots.btn.unsubscribe": { en: "Unsubscribe", ar: "إلغاء الاشتراك" },
    "bots.btn.unsub": { en: "Unsub", ar: "إلغاء" },
    "bots.btn.login": { en: "Login", ar: "تسجيل الدخول" },
    "bots.active_days": { en: "{days} Days Active", ar: "{days} يوم نشط" },
    "bots.inactive": { en: "Inactive", ar: "غير نشط" },
    "bots.banner_title": { en: "Top Stocks", ar: "أفضل الأسهم" },
    "bots.banner_desc": { en: "Top popular EGX stocks ranked by AI Score based on advanced machine learning models.", ar: "أفضل أسهم البورصة المصرية وأكثرها شعبية مرتبة حسب تقييم الذكاء الاصطناعي بناءً على نماذج التعلم الآلي المتقدمة." },
    "bots.limit_reached": { en: "Subscription Limit Reached", ar: "تم الوصول للحد الأقصى للاشتراك" },
    "model.size": { en: "Size", ar: "الحجم" },
    "model.modified": { en: "Modified", ar: "تاريخ التعديل" },
    "model.features": { en: "Features", ar: "ميزات" },
    "model.trees": { en: "Trees", ar: "أشجار" },
    "model.samples": { en: "Samples", ar: "عينات" },
    "model.lr": { en: "Learning Rate", ar: "معدل التعلم" },
    "model.index_json": { en: "Index JSON", ar: "مؤشر السوق" },
    "model.fundamentals": { en: "Fundamentals", ar: "التحليل الأساسي" },
    "model.meta_labeling": { en: "Meta-Labeling", ar: "التصنيف التلوي" },
    "model.target": { en: "Target", ar: "الهدف" },
    "model.stop": { en: "Stop", ar: "الوقف" },
    "model.days": { en: "Days", ar: "الأيام" },
    "backtest.win_rate": { en: "Win Rate", ar: "نسبة النجاح" },
    "backtest.net_profit": { en: "Total Return", ar: "العائد الكلي" },
    "backtest.total_trades": { en: "Total Trades", ar: "إجمالي الصفقات" },
    "backtest.avg_return": { en: "Avg Return / Trade", ar: "متوسط العائد / صفقة" },
    "backtest.hide_trades": { en: "Hide Trades", ar: "إخفاء الصفقات" },
    "backtest.view_trades": { en: "View Trade Logs", ar: "عرض سجل الصفقات" },
    "backtest.days_active": { en: "Days Active", ar: "يوم نشط" },
    "backtest.vs_egx": { en: "vs EGX30", ar: "مقابل مؤشر EGX30" },
    "backtest.no_models_found": { en: "No local models found on server.", ar: "لم يتم العثور على نماذج محلية على الخادم." },
    "backtest.loading_models": { en: "Fetching models...", ar: "جاري جلب النماذج..." },
    "backtest.details": { en: "Backtest Details", ar: "تفاصيل الاختبار العكسي" },
    "backtest.simulation_radar": { en: "Simulation Radar Analysis", ar: "تحليل محاكاة الرادار" },
    "backtest.table.symbol": { en: "Symbol", ar: "الرمز" },
    "backtest.table.entry_date": { en: "Entry Date", ar: "تاريخ الدخول" },
    "backtest.table.exit_date": { en: "Exit Date", ar: "تاريخ الخروج" },
    "backtest.table.score": { en: "Score", ar: "التقييم" },
    "backtest.table.pl": { en: "P/L", ar: "الربح/الخسارة" },
    "backtest.table.status": { en: "Status", ar: "الحالة" },
    "backtest.table.days": { en: "Days", ar: "الأيام" },
    "backtest.council": { en: "Council:", ar: "المجلس:" },
    "backtest.meta": { en: "Meta:", ar: "البيانات الفوقية:" },
    "backtest.table.dates": { en: "Dates (In / Out)", ar: "التواريخ (دخول / خروج)" },
    "backtest.table.timing": { en: "Timing", ar: "التوقيت" },
    "backtest.table.pricing": { en: "Pricing (In / Out)", ar: "الأسعار (دخول / خروج)" },
    "backtest.table.radar_score": { en: "Radar Score", ar: "تقييم الرادار" },
    "backtest.table.fund_score": { en: "Fund Score", ar: "التقييم الأساسي" },
    "backtest.table.pl_pct": { en: "P/L %", ar: "الربح/الخسارة %" },
    "backtest.table.in": { en: "In: ", ar: "دخول: " },
    "backtest.table.out": { en: "Out: ", ar: "خروج: " },
    "backtest.status.accepted": { en: "Accepted", ar: "مقبول" },
    "backtest.status.rejected": { en: "Rejected", ar: "مرفوض" },
    "backtest.strategy_only": { en: "Strategy Only", ar: "الاستراتيجية فقط" },
    "backtest.pre_council": { en: "Pre-Council", ar: "قبل المجلس" },
    "backtest.with_filter": { en: "With Filter", ar: "مع التصفية" },
    "backtest.post_council": { en: "Post-Council", ar: "بعد المجلس" },
    "backtest.trade_reduction": { en: "Trade Reduction", ar: "تقليص الصفقات" },
    "backtest.winrate_boost": { en: "Win Rate Boost", ar: "تعزيز نسبة النجاح" },
    "backtest.actual_range": { en: "Actual Range", ar: "النطاق الفعلي" },
    "backtest.stats.title": { en: "Model Performance Dashboard", ar: "لوحة أداء الموديل" },
    "backtest.stats.desc": { en: "Cumulative historical performance overview per model based on EGX backtest runs.", ar: "عرض عام لأداء الموديل التاريخي المتراكم بناءً على نتائج محاكاة البورصة المصرية." },
    "backtest.stats.total_runs": { en: "Total Runs", ar: "إجمالي الاختبارات" },
    "backtest.stats.total_trades": { en: "Total Trades", ar: "إجمالي الصفقات" },
    "backtest.stats.win_rate": { en: "Combined Win Rate", ar: "نسبة النجاح العامة" },
    "backtest.stats.avg_profit": { en: "Avg Total Return / Run", ar: "متوسط العائد الكلي / اختبار" },
    "backtest.stats.avg_return": { en: "Avg Return / Trade", ar: "متوسط العائد / صفقة" },
    "backtest.audit.title": { en: "Council Audit: Member Efficiency", ar: "تدقيق المجلس: كفاءة الأعضاء" },
    "backtest.audit.killed": { en: "{count} Profitable Trades Killed", ar: "تم إلغاء {count} صفقة رابحة" },
    "backtest.audit.desc": { 
        en: "The council filtered out {count} opportunities that would have resulted in a profit. Review the voting logs below to identify which member is being too conservative.", 
        ar: "قام المجلس بتصفية {count} من الفرص التي كانت ستؤدي إلى ربح. راجع سجلات التصويت أدناه لتحديد أي الأعضاء كان متحفظاً للغاية." 
    },
    "backtest.audit.suspicious": { en: "Suspicious Member", ar: "العضو المشتبه به" },
    "backtest.audit.suspicious_val": { en: "RSI / Fundamental?", ar: "مؤشر RSI / الأساسي؟" },
    "backtest.audit.suspicious_desc": { en: "Check 'NO' votes on filtered wins.", ar: "راجع أصوات 'لا' على الأرباح المصفاة." },
    "backtest.audit.impact": { en: "Council Impact", ar: "تأثير المجلس" },
    "backtest.audit.impact_winrate": { en: "+{winrate}% Win Rate", ar: "+{winrate}% نسبة النجاح" },
    "backtest.audit.impact_desc": { en: "Net win rate improvement.", ar: "تحسن صافي نسبة النجاح." },
    "backtest.audit.action": { en: "Action Required", ar: "الإجراء المطلوب" },
    "backtest.audit.action_refine": { en: "Refine Weights", ar: "تحسين الأوزان" },
    "backtest.audit.action_desc": { en: "Consider lowering the 'King' weight.", ar: "ضع في اعتبارك خفض وزن 'الملك'." },
    "backtest.exchange_label": { en: "Exchange:", ar: "البورصة:" },
    "backtest.run_id_label": { en: "Run ID:", ar: "معرف التشغيل:" },
    "bots.subscribed": { en: "Subscribed", ar: "مشترك" },
    "bots.mode.aggressive": { en: "Aggressive", ar: "نشط" },
    "bots.mode.defensive": { en: "Defensive", ar: "حذر" },
    "bots.mode.hybrid": { en: "Hybrid", ar: "متوازن" },
    "bots.btn.login_to_sub": { en: "Login to Subscribe", ar: "سجل الدخول للاشتراك" },
    "blogs.label": { en: "Market Blogs & Insights", ar: "مدونات السوق والرؤى" },
    "blogs.heading": { en: "Expert Analysis", ar: "تحليل الخبراء" },
    "blogs.description": { en: "Deep dives into market trends, algorithmic strategies, and the future of AI-driven finance.", ar: "تحليلات معمقة لاتجاهات السوق والاستراتيجيات الخوارزمية ومستقبل التمويل المدفوع بالذكاء الاصطناعي." },
    "blogs.author": { en: "Author", ar: "المؤلف" },
    "blogs.close": { en: "Close", ar: "إغلاق" },
    "telegram.alerts.title": { en: "Telegram Alerts", ar: "تنبيهات تليجرام" },
    "telegram.alerts.inactive_title": { en: "Telegram Username Inactive!", ar: "معرف تيليجرام غير مفعّل!" },
    "telegram.alerts.inactive_desc": { 
        en: "To receive technical alerts, please go to the Profile page, set your Telegram Chat ID, and activate the bot.", 
        ar: "لتلقي التنبيهات الفنية، يرجى التوجه لصفحة الملف الشخصي وتعيين معرف تيليجرام الخاص بك، ثم تفعيل البوت." 
    },
    "telegram.alerts.active_alerts": { en: "Active Alerts", ar: "التنبيهات النشطة" },
    "telegram.alerts.create_alert": { en: "Create Alert", ar: "إنشاء تنبيه" },
    "telegram.alerts.no_alerts": { en: "No Technical Alerts Set", ar: "لم يتم تعيين أي تنبيهات فنية" },
    "telegram.alerts.delete_tooltip": { en: "Delete alert", ar: "حذف التنبيه" },
    "telegram.alerts.create_title": { en: "Create Telegram Alert", ar: "إنشاء تنبيه تليجرام" },
    "telegram.alerts.alert_name": { en: "Alert Name", ar: "اسم التنبيه" },
    "telegram.alerts.name_placeholder": { en: "e.g. RSI Oversold EGX Stocks", ar: "مثال: أسهم البورصة المصرية RSI Oversold" },
    "telegram.alerts.filters_included": { en: "Active Filters Included:", ar: "الفلاتر النشطة المضمنة:" },
    "telegram.alerts.filter.market": { en: "Market", ar: "السوق" },
    "telegram.alerts.filter.egypt": { en: "Egypt (EGX)", ar: "مصر (EGX)" },
    "telegram.alerts.filter.min_price": { en: "Min Price", ar: "أقل سعر" },
    "telegram.alerts.filter.rsi": { en: "RSI", ar: "مؤشر RSI" },
    "telegram.alerts.filter.min_mcap": { en: "Min Market Cap", ar: "أقل قيمة سوقية" },
    "telegram.alerts.filter.max_mcap": { en: "Max Market Cap", ar: "أقصى قيمة سوقية" },
    "telegram.alerts.filter.sector": { en: "Sector", ar: "القطاع" },
    "telegram.alerts.filter.above_ema50": { en: "Price > EMA 50", ar: "السعر > EMA 50" },
    "telegram.alerts.filter.above_ema200": { en: "Price > EMA 200", ar: "السعر > EMA 200" },
    "telegram.alerts.filter.golden_cross": { en: "Golden Cross", ar: "التقاطع الذهبي" },
    "telegram.alerts.filter.vol_above_sma20": { en: "Vol > SMA 20", ar: "الحجم > SMA 20" },
    "telegram.alerts.filter.above_vwap20": { en: "Price > VWAP 20", ar: "السعر > VWAP 20" },
    "telegram.alerts.filter.ai_predictions": { en: "AI Predictions", ar: "توقعات الذكاء الاصطناعي" },
    "telegram.alerts.filter.yes": { en: "Yes", ar: "نعم" },
    "telegram.alerts.cancel": { en: "Cancel", ar: "إلغاء" },
    "telegram.alerts.save_btn": { en: "Save Alert", ar: "حفظ التنبيه" },
    "profile.notification.title": { en: "Notification Settings", ar: "إعدادات الإشعارات" },
    "profile.notification.subtitle": { en: "Choose where you want to receive real-time trading bot alerts (Only one channel allowed)", ar: "اختر أين تفضل استلام إشارات وتنبيهات بوتات التداول الفورية (مسموح بطريقة واحدة فقط)" },
    "profile.notification.channel": { en: "Notification Channel", ar: "طريقة الاستلام" },
    "profile.notification.channel.telegram": { en: "Telegram Channel", ar: "قناة تليجرام" },
    "profile.notification.telegram.linked": { en: "Connected successfully", ar: "مرتبط بنجاح" },
    "profile.notification.telegram.not_linked": { en: "Not connected", ar: "غير مرتبط" },
    "profile.notification.telegram.desc": { en: "Link your profile instantly by clicking the button below and hitting 'Start' in the bot chat.", ar: "اربط حسابك فورياً بالضغط على الزر أدناه والضغط على 'ابدأ' داخل محادثة البوت." },
    "profile.notification.telegram.btn": { en: "Connect Telegram Bot", ar: "ربط حساب تليجرام" },
    "profile.notification.telegram.status": { en: "Telegram Status", ar: "حالة تليجرام" },
    "profile.notification.channel.select": { en: "Select Channel", ar: "اختر طريقة استلام الإشعارات" },
    // Auth (Login / Signup)
    "auth.login.title": { en: "Login", ar: "تسجيل الدخول" },
    "auth.login.subtitle": { en: "Sign in to sync your watchlist and settings.", ar: "سجل الدخول لمزامنة قائمة المراقبة والإعدادات." },
    "auth.email": { en: "Email", ar: "البريد الإلكتروني" },
    "auth.password": { en: "Password", ar: "كلمة المرور" },
    "auth.signin_btn": { en: "Sign in", ar: "تسجيل الدخول" },
    "auth.signingin_btn": { en: "Signing in...", ar: "جاري تسجيل الدخول..." },
    "auth.signin_google": { en: "Sign in with Google", ar: "تسجيل الدخول بواسطة جوجل" },
    "auth.or": { en: "Or", ar: "أو" },
    "auth.login.no_account": { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
    "auth.login.create_one": { en: "Create one", ar: "أنشئ حساباً جديداً" },
    "auth.signup.title": { en: "Create account", ar: "إنشاء حساب" },
    "auth.signup.subtitle": { en: "Sign up to sync watchlist, targets, and stats.", ar: "سجل مجاناً لمزامنة قائمة المراقبة، الأهداف، والإحصائيات." },
    "auth.email_placeholder": { en: "you@example.com", ar: "you@example.com" },
    "auth.password_placeholder": { en: "At least 6 characters", ar: "٦ أحرف على الأقل" },
    "auth.create_btn": { en: "Create account", ar: "إنشاء الحساب" },
    "auth.creating_btn": { en: "Creating...", ar: "جاري الإنشاء..." },
    "auth.signup.have_account": { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
    "auth.signup.login": { en: "Login", ar: "تسجيل الدخول" },
    // Footer
    "footer.tagline": {
        en: "EGX stock analysis platform with AI score, technical scanner, historical similarity, and backtests.",
        ar: "منصة تحليل أسهم البورصة المصرية بتقييم الذكاء الاصطناعي، الماسح الفني، النماذج التاريخية، والمحاكاة التاريخية."
    },
    "footer.platform": { en: "Platform", ar: "المنصة" },
    "footer.resources": { en: "Resources", ar: "الموارد" },
    "footer.blogs": { en: "Market Blogs", ar: "مدونات السوق" },
    "footer.faq": { en: "FAQ", ar: "الأسئلة الشائعة" },
    "footer.copyright": {
        en: "© 2026 EGX BOTS. Built for EGX analysis.",
        ar: "© 2026 EGX BOTS. صُمم لتحليل البورصة المصرية."
    },
    // Sharia-compliant filter
    "filter.sharia": { en: "Sharia Compliant", ar: "متوافقة شرعياً" },
    "filter.sharia_only": { en: "Sharia-Compliant Only", ar: "المتوافقة شرعياً فقط" },
    "filter.sharia_hint": {
        en: "Show only EGX stocks screened for Sharia compliance (excludes banks, insurance, alcohol, tobacco & pork).",
        ar: "عرض أسهم البورصة المصرية المتوافقة شرعياً فقط (يستثني البنوك والتأمين والكحول والتبغ ولحم الخنزير)."
    },
    "filter.sharia_badge": { en: "Halal", ar: "حلال" },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>("ar"); // Default is Arabic

    useEffect(() => {
        const stored = localStorage.getItem("app-language") as Language;
        const defaultLang = stored === "en" || stored === "ar" ? stored : "ar";
        setLanguageState(defaultLang);
        document.documentElement.dir = "ltr";
        document.documentElement.lang = defaultLang;
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("app-language", lang);
        document.documentElement.dir = "ltr";
        document.documentElement.lang = lang;
    };

    const dir = "ltr";

    const t = (key: string) => {
        const entry = translations[key];
        if (!entry) return key;
        return entry[language] || entry["en"];
    };

    return (
        <LanguageContext.Provider
            value={{
                language,
                setLanguage,
                t,
                dir,
            }}
        >
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
