UPDATE stock_fundamentals SET name_ar = 'الشمس' WHERE symbol = 'ELSH' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'التجاري' WHERE symbol = 'COMI' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'فوري' WHERE symbol = 'FWRY' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'طلعت' WHERE symbol = 'TMGH' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'عز, حديد عز' WHERE symbol = 'ESRS' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'بلتون' WHERE symbol = 'BTFH' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'هيرميس' WHERE symbol = 'HRHO' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'الشرقية للدخان, ايسترن' WHERE symbol = 'EAST' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'عامر' WHERE symbol = 'AMER' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'السويدي' WHERE symbol = 'SWDY' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'موبكو' WHERE symbol = 'MFPC' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'ابو قير, أبو قير, ابوقير' WHERE symbol = 'ABUK' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'سيدي كرير' WHERE symbol = 'SKPC' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'اموك, أموك' WHERE symbol = 'AMOC' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'بالم هيلز' WHERE symbol = 'PHDC' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'مدينة نصر' WHERE symbol = 'MNHD' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'مصر الجديدة' WHERE symbol = 'HELI' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'جهينة' WHERE symbol = 'JUFO' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'ايديتا, إيديتا' WHERE symbol = 'EFID' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'ابن سينا' WHERE symbol = 'ISPH' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'سوديك' WHERE symbol = 'OCDI' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'أوراسكوم' WHERE symbol = 'ORHD' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'بايونيرز' WHERE symbol = 'PRDC' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'دايس' WHERE symbol = 'DSCW' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'سبيد' WHERE symbol = 'SPMD' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'مستشفى كليوباترا' WHERE symbol = 'CLHO' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'كريدي اجريكول' WHERE symbol = 'CIEB' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'ابو ظبي' WHERE symbol = 'ADIB' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'القلعة' WHERE symbol = 'CCAP' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'جي بي اوتو' WHERE symbol = 'AUTO' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'راية' WHERE symbol = 'RAYA' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'النساجون' WHERE symbol = 'ORWE' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'مكادي' WHERE symbol = 'MCQE' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'زهراء المعادي' WHERE symbol = 'ZMID' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'كيما' WHERE symbol = 'EGCH' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'القاهرة للدواجن' WHERE symbol = 'POUL' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'دومتي' WHERE symbol = 'DOMT' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'عبور لاند' WHERE symbol = 'OLFI' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'راميدا' WHERE symbol = 'RMDA' AND name_ar IS NULL;
UPDATE stock_fundamentals SET name_ar = 'سيرا' WHERE symbol = 'CIRA' AND name_ar IS NULL;
