"use client";

import { useLanguage } from "@/contexts/LanguageContext";
import {
  ShieldAlert,
  AlertTriangle,
  TrendingUp,
  Info,
  FileText,
  Sparkles,
  ArrowRight,
} from "lucide-react";
import Link from "next/link";

export default function DisclaimerClient() {
  const { language } = useLanguage();
  const isAr = language === "ar";

  const sections = [
    {
      icon: <ShieldAlert className="w-6 h-6 text-black" />,
      title: {
        en: "Not Financial Advice",
        ar: "ليست نصيحة مالية استثمارية"
      },
      content: {
        en: "All model outputs, predictions, technical scanner results, similarity models, and backtesting metrics generated by EGX BOTS are algorithmically derived and provided for educational and informational purposes only. EGX BOTS does not provide investment or financial advice. None of the content on this website should be construed as a solicitation, recommendation, or endorsement to buy or sell any security.",
        ar: "جميع مخرجات نماذج الذكاء الاصطناعي، التوقعات، نتائج الماسح الفني، النماذج التاريخية، وتقييمات المحاكاة المعروضة على منصة EGX BOTS هي مخرجات خوارزمية مؤتمتة ويتم تقديمها لأغراض تعليمية وإعلامية فقط. لا تقدم المنصة أي نصائح استثمارية أو توصيات مالية. لا ينبغي تفسير أي محتوى في هذا الموقع كطلب أو توصية أو تأييد لشراء أو بيع أي ورقة مالية."
      }
    },
    {
      icon: <TrendingUp className="w-6 h-6 text-black" />,
      title: {
        en: "Trading & Investment Risk",
        ar: "مخاطر التداول والاستثمار"
      },
      content: {
        en: "Trading and investing in the Egyptian Exchange (EGX) and financial markets carry high levels of risk and may not be suitable for all investors. You could lose all or more than your initial investment. Past performance of our AI models (such as model_EGX or KING) is not indicative or a guarantee of future results. You are solely responsible for your own investment decisions and any losses incurred.",
        ar: "ينطوي التداول والاستثمار في البورصة المصرية (EGX) وأسواق المال على مستويات عالية من المخاطر وقد لا يكون مناسباً لجميع المستثمرين. قد تخسر جزءاً من رأس مالك أو كامل استثمارك الأولي. الأداء التاريخي السابق لنماذج الذكاء الاصطناعي لدينا (مثل model_EGX أو KING) لا يضمن ولا يعتبر مؤشراً للنتائج المستقبلية. أنت وحدك المسؤول عن قراراتك الاستثمارية وأي خسائر قد تتكبدها."
      }
    },
    {
      icon: <Info className="w-6 h-6 text-black" />,
      title: {
        en: "Data Accuracy & Reliability",
        ar: "دقة وموثوقية البيانات"
      },
      content: {
        en: "Market prices, corporate fundamentals, and technical indicators are sourced from third-party data providers (e.g., EODHD). While we strive to ensure the accuracy and reliability of the data displayed, we make no representations or warranties as to its completeness, timeliness, correctness, or availability. Delays, data feed failures, or service disruptions may occur.",
        ar: "يتم الحصول على أسعار السوق، البيانات الأساسية للشركات، والمؤشرات الفنية من مزودي بيانات خارجيين (مثل EODHD). على الرغم من أننا نبذل قصارى جهدنا لضمان دقة وموثوقية البيانات المعروضة، إلا أننا لا نقدم أي ضمانات بشأن اكتمالها أو توقيتها أو صحتها أو توافرها. قد تحدث تأخيرات أو انقطاعات في البيانات أو انقطاع الخدمة."
      }
    },
    {
      icon: <FileText className="w-6 h-6 text-black" />,
      title: {
        en: "Limitation of Liability",
        ar: "حدود المسؤولية القانونية"
      },
      content: {
        en: "To the maximum extent permitted by law, EGX BOTS, its developers, operators, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or punitive damages, including but not limited to loss of profits, trading losses, or data loss arising out of the use or inability to use this platform.",
        ar: "إلى أقصى حد يسمح به القانون، لا تتحمل منصة EGX BOTS أو مطوروها أو مشغلوها أو الكيانات التابعة لها المسؤولية عن أي خسائر مالية أو أضرار مباشرة أو غير مباشرة أو عرضية أو تبعية أو عقابية، بما في ذلك على سبيل المثال لا الحصر، خسائر الأرباح أو خسائر التداول الناتجة عن استخدام أو عدم القدرة على استخدام هذه المنصة."
      }
    }
  ];

  return (
    <div className="neobrutal-layout flex flex-col gap-12 pb-20 pt-2 relative -mx-3 sm:-mx-6 md:-mx-8 px-4 md:px-8 min-h-screen neobrutal-grid-bg">
      {/* Header section */}
      <header className="space-y-4 max-w-3xl pt-8">
        <div className="inline-flex items-center gap-2 border-4 border-black dark:border-white px-4 py-2 neobrutal-bg-yellow font-black text-xs sm:text-sm uppercase tracking-widest rotate-[-1deg] shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,1)] hover:rotate-0 transition-transform duration-200 cursor-pointer">
          <AlertTriangle className="w-4 h-4 text-black" />
          <span className="text-black">
            {isAr ? "إخلاء مسؤولية قانوني" : "Legal Disclaimer"}
          </span>
        </div>
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-black tracking-tighter text-black dark:text-white uppercase drop-shadow-[4px_4px_0px_rgba(0,0,0,1)] dark:drop-shadow-[4px_4px_0px_rgba(255,255,255,0.15)] pt-2">
          {isAr ? "إخلاء المسؤولية والتحذيرات" : "Disclaimer & Warnings"}
        </h1>
        <p className="text-zinc-800 dark:text-zinc-300 text-base sm:text-lg max-w-2xl font-bold leading-relaxed">
          {isAr
            ? "يرجى قراءة بنود إخلاء المسؤولية القانونية وفهم طبيعة المخاطر المرتبطة بالتداول في البورصة واستخدام نماذج الذكاء الاصطناعي."
            : "Please read the legal disclaimer clauses and understand the nature of risks associated with trading and using AI models."}
        </p>
      </header>

      {/* Grid of Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {sections.map((section, idx) => (
          <div
            key={idx}
            className="border-4 border-black dark:border-white bg-white dark:bg-zinc-950 p-6 sm:p-8 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] dark:shadow-[6px_6px_0px_0px_rgba(255,255,255,1)] hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] dark:hover:shadow-[8px_8px_0px_0px_rgba(255,255,255,1)] transition-all duration-200"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 border-4 border-black dark:border-white neobrutal-bg-yellow flex items-center justify-center shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] dark:shadow-[3px_3px_0px_0px_rgba(255,255,255,1)]">
                {section.icon}
              </div>
              <h2 className="text-lg sm:text-xl font-black text-black dark:text-white uppercase tracking-tight">
                {section.title[language]}
              </h2>
            </div>
            <p className="text-sm sm:text-base text-zinc-800 dark:text-zinc-300 font-semibold leading-relaxed">
              {section.content[language]}
            </p>
          </div>
        ))}
      </div>

      {/* Warning CTA Box */}
      <section className="mt-4 border-4 border-black dark:border-white bg-[#fb923c] dark:bg-amber-500 p-8 sm:p-12 text-center space-y-6 relative overflow-hidden shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] dark:shadow-[8px_8px_0px_0px_rgba(255,255,255,1)] hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[10px_10px_0px_0px_rgba(0,0,0,1)] dark:hover:shadow-[10px_10px_0px_0px_rgba(255,255,255,1)] transition-all duration-200">
        <div className="w-14 h-14 border-4 border-black neobrutal-bg-yellow flex items-center justify-center mx-auto shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]">
          <Sparkles className="w-7 h-7 text-black" />
        </div>

        <h2 className="text-2xl sm:text-3xl font-black text-black uppercase tracking-tight">
          {isAr ? "إقرار المستخدم بالموافقة" : "User Consent & Agreement"}
        </h2>
        <p className="text-black max-w-2xl mx-auto text-sm sm:text-base font-extrabold leading-relaxed">
          {isAr
            ? "باستخدامك لمنصة EGX BOTS أو تصفحك لأي من محتوياتها أو اشتراكك في إشاراتها وتنبيهاتها، فإنك تقر بأنك قد قرأت إخلاء المسؤولية هذا وتفهمه بالكامل، وتوافق على شروطه وتتحمل مسؤولية جميع تداولاتك بشكل كامل وحصري."
            : "By using EGX BOTS, browsing its content, or subscribing to its alerts and signals, you acknowledge that you have read and understood this legal disclaimer, agree to its terms, and assume full and exclusive responsibility for all your trading actions."}
        </p>

        <div className="flex flex-col sm:flex-row gap-4 max-w-md mx-auto pt-2">
          <Link
            href="/"
            className="h-14 px-8 border-4 border-black bg-black text-white text-xs font-black uppercase tracking-widest hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[4px_4px_0px_0px_rgba(255,255,255,1)] active:translate-x-[2px] active:translate-y-[2px] active:shadow-none transition-all duration-100 cursor-pointer flex items-center justify-center gap-2"
          >
            {isAr ? "الرئيسية" : "Home"}
            <ArrowRight
              className={`w-4 h-4 ${isAr ? "rotate-180" : ""}`}
            />
          </Link>
          <Link
            href="/scanner/technical"
            className="h-14 px-8 border-4 border-black bg-white text-black text-xs font-black uppercase tracking-widest hover:translate-x-[-2px] hover:translate-y-[-2px] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] active:translate-x-[2px] active:translate-y-[2px] active:shadow-none transition-all duration-100 cursor-pointer flex items-center justify-center"
          >
            {isAr ? "ابدأ الفحص الفني" : "Technical Scanner"}
          </Link>
        </div>
      </section>
    </div>
  );
}
